### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by emign** [NorthernRealities/ColorSenseRainbow#2]
Am I too silly ?
I do not know, how to use this plugin. What is a carat? :)

**Comment by NorthernRealities** [comment]
Hi.  After you have installed the plugin and restarted Xcode you move the carat (the item in the window that tells you where the next character you type will be put) somewhere within the code that defines either a UIColor or NSColor object.  At this point you should see a box be drawn around the code and a sample of the colour show up above the code at the right.  You can see what this should look like in the [description of the project](https://github.com/NorthernRealities/ColorSenseRainbow).  

If you click on the sample of the colour then the Color Picker will be brought up.  You can then select different colours or change the alpha component and your code will be modified to match the new values.  After you are done just close the Color Picker.  If you don't like the changes you made with the picker you can just undo them.

**Comment by emign** [comment]
Thank you. Actually I really was blind. I never passed the color values as
fractions 246/255. I passed absolute values: 246
This does not trigger the color plugin =)

2015-06-17 19:48 GMT+02:00 Reid Gravelle notifications@github.com:

**Comment by NorthernRealities** [comment]
Hi,

I’m glad you got it sorted out.  If you are working in Swift you might be interested in my Rainbow-Creator repository (https://github.com/NorthernRealities/Rainbow-Creator).  I’ve forgotten to divide the numbers by 255 plenty of times and one of the functions I have in this extension allows you to create colours without having to divide.  The alpha component has a default value of 1.0 so if that is what you want then you don’t have to include it when you create the colour.  I also thought that code looks cleaner without all of the /255 in it.

I’ve included another function that let’s you create colours without specifying alpha value but you specify values for red, green, and blue between 0 and 1.  It just calls the normal function with an alpha of 1.0.  There are also a couple of functions that let you create colours with hexadecimal strings and integers.

Reid.

**Comment by revolter** [comment]
Hi, for some reason, upon changing the RGBA values in the popup box, the code is left intact, any idea why is this happening?

**Comment by NorthernRealities** [comment]
Hi.  I know that sometimes when I use try to use the popup box to change the values for code that I didn't open the popup box with it won't change the values.  I'm looking into why that is but I've always been able to close the popup and re-open it again by clicking on the colour sample that's shown for the code that I want to modify.

**Comment by revolter** [comment]
I tried closing and opening it multiple times, to no avail

**Comment by NorthernRealities** [comment]
Hi,

In order to try and help diagnose the issue it would be helpful to know more about the problem.  What version of Xcode are you running?  What version of Mac OS X?  How are you opening the color picker?  What is the code defining a color not being updated?  Is it all colors not being updated or just a particular one?  Are you seeing samples of colours?  Anything else would be helpful.

Thanks.

**Comment by revolter** [comment]
> What version of Xcode are you running?

`Version 6.4 (6E35b)`

> What version of Mac OS X?

`Yosemite Version 10.10.3 (14D136)`

> How are you opening the color picker?

By clicking on the code that creates the color and then on the upper-right color preview.

> What is the code defining a color not being updated?

For example, `[UIColor whiteColor]`.
- If I try to change one of the R, G or B channels, it changes the code to `[UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1.0]` and it stays like this.
- If I try to change the alpha channel, it changes the code to `[UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 0.99]` and it stays like this.

> Is it all colors not being updated or just a particular one?

From what I say, I guess that it's for all colors.
For `[UIColor colorWithRed:1 green:1 blue:1 alpha:0.1]` and `[UIColor colorWithRed:0.298 green:0.855 blue:0.392 alpha:1]` the color preview doesn't appear at all.

**Comment by NorthernRealities** [comment]
Hi,

Thanks for the details.  I've just put up a new release and I hope that it takes care of the problem.  What was happening is the plugin didn't accept 0 or 1 as a valid value.  It expected 0.0 or 1.0 instead.  That's why the colour previews weren't showing up.

With the whiteColor there was another bug.  The code that wrote the new values didn't put on the ".0" which brought about the previous bug.
