### ISSUE TITLE
Remove spaces after colon!

### ISSUE THREAD

**Issue by revolter** [NorthernRealities/ColorSenseRainbow#9]

**Comment by NorthernRealities** [comment]
If you don’t provide any details with your request then how is anyone supposed to know what you mean.  I’m not going to guess.

**Comment by revolter** [comment]
_(Sorry, I had a bad morning)_ The plugin shouldn't add spaces after colons, so it should change the code to something like `colorWithRed:0.4 green:0.2 blue:0.6 alpha:1` instead of `colorWithRed: 0.4 green: 0.2 blue: 0.6 alpha: 1`.

**Comment by NorthernRealities** [comment]
When does it do this?

**Comment by revolter** [comment]
It looks like it doesn't do this anymore or I can't reproduce it. But even the screenshot in the `README` shows spaces. I'll close it until I have more information.

**Comment by revolter** [comment]
@NorthernRealities, Hi, I can reproduce it again using these steps:
- write `[UIColor blackColor];`
- click anywhere inside the written code
- click the color preview rectangle
- drag the alpha slider to `50%`

it should change the original code to `[UIColor colorWithRed: 0.0 green: 0.0 blue: 0.0 alpha: 0.5];` instead of `[UIColor colorWithRed:0.0 green:0.0 blue:0.0 alpha:0.5];`

**Comment by NorthernRealities** [comment]
I've made the change to the code and uploaded it.

Before:
<img width="300" alt="screen shot 2015-08-02 at 14 23 36" src="https://cloud.githubusercontent.com/assets/11425858/9027402/351a48f8-3922-11e5-923f-5603e37582d2.png">

After:
<img width="616" alt="screen shot 2015-08-02 at 14 23 50" src="https://cloud.githubusercontent.com/assets/11425858/9027405/3b58535e-3922-11e5-9240-0d53b8348925.png">

**Comment by NorthernRealities** [comment]
You're welcome.
